title = "Osync I/O"
baseURL = "https://osync.io"
hasCJKLanguage = true
enableGitInfo = true
googleAnalytics = "G-JQCHZM9PGG"

[menu]

  [[menu.nav]]
    name = "Posts"
    url = "/posts"
    weight = 1

  [[menu.nav]]
    name = "Tags"
    url = "/tags"
    weight = 2

  [[menu.nav]]
    name = "About"
    url = "/about"
    weight = 3

  [[menu.footer]]
    name = "Discord"
    url = "https://discord.gg/JhgFz8u"
    weight = 1

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/oshinko"
    weight = 2

  [[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/Osynco"
    weight = 3

  [[menu.footer]]
    name = "Steam"
    url = "https://steamcommunity.com/id/Osh1nko"
    weight = 4

  [[menu.footer]]
    name = "Nostr"
    url = "https://snort.social/p/npub1xx3kyu57uqukvsxmlhnmafv825pct93455hkn544nd6exlnunxps2psn5q"
    weight = 5

[params]
  description = "野良プログラマーおしんこのブログ"
  image = "/default.png"
