title = "Osync I/O"
baseURL = "http://osync.io"
hasCJKLanguage = true
enableGitInfo = true
googleAnalytics = "G-JQCHZM9PGG"

[menu]

  [[menu.nav]]
    name = "Posts"
    url = "/posts"
    weight = 1

  [[menu.nav]]
    name = "Tags"
    url = "/tags"
    weight = 2

  [[menu.nav]]
    name = "About"
    url = "/about"
    weight = 3

  [[menu.footer]]
    name = "Discord"
    url = "https://discord.gg/JhgFz8u"
    weight = 1

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/oshinko"
    weight = 2

  [[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/Osynco"
    weight = 3

  [[menu.footer]]
    name = "Steam"
    url = "https://steamcommunity.com/id/Osh1nko"
    weight = 4

[params]
  description = "ゲーム好きプログラマーおしんこのブログ"
  image = "/default.png"
